name: app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_tts: ^3.2.0
  speech_to_text: ^7.0.0
  audioplayers: ^6.4.0
  flutter_svg: ^2.1.0
  translator: ^1.0.3+1
  font_awesome_flutter: ^10.8.0
  http: ^1.4.0
  shared_preferences: ^2.5.3
  connectivity_plus: ^4.0.2
  internet_connection_checker: ^1.0.0+1
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/image/logo1.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/sounds/click.mp3
    - assets/sounds/click8bit.mp3
    - assets/sounds/checktrue.wav
    - assets/sounds/checkfalse.mp3
    - assets/icons/booka96.png
    - assets/icons/bookdic100.png
    - assets/icons/game96.png
    - assets/icons/profile80.png
    - assets/icons/star96.png
    - assets/icons/banana96.png
    - assets/icons/banana.png
    - assets/icons/monkey64.png
    - assets/icons/guess.png
    - assets/icons/match.png
    - assets/icons/add.png
    - assets/icons/pic.png
    - assets/icons/speak.png
    - assets/icons/worm.png
    - assets/image/monkey.png
    - assets/image/bg.png
    - assets/image/logo1.png
    - assets/image/home.png
    - assets/image/sport.png
    - assets/image/animal.png
    - assets/image/vehicle.png
    - assets/image/avatar_0.png
    - assets/image/avatar_1.png
    - assets/image/avatar_2.png
    - assets/image/avatar_3.png
    - assets/image/avatar_4.png
    - assets/image/avatar_5.png
    - assets/image/home1.png
    - assets/image/home2.png
    - assets/image/home3.png
    - assets/image/translate.png
    - assets/icons/translatepic.png

